<?php

declare (strict_types=1);
namespace Codeception\Lib\Generator;

use Codeception\Codecept;
use Codeception\Configuration;
use Codeception\Lib\Di;
use Codeception\Lib\Generator\Shared\Classname;
use Codeception\Lib\Module_Container;
use Codeception\Step\Generated_Step;
use Codeception\Util\Reflection_Helper;
use Codeception\Util\Template;
use Exception;
use function implode;
use InvalidArgumentException;
use Reflection_Attribute;
use ReflectionClass;
use Reflection_Exception;
use ReflectionIntersectionType;
use ReflectionMethod;
use ReflectionNamedType;
use Reflection_Type;
use ReflectionUnionType;
use function sprintf;
class Actions
{
    use Classname;
    public Di $di;
    public Module_Container $module_container;
    protected string $template = <<<EOF
    <?php  //[STAMP] {{hash}}
    // phpcs:ignoreFile
    namespace {{namespace}}_generated;
    
    // This class was automatically generated by build task
    // You should not change it manually as it will be overwritten on next build
    
    trait {{name}}Actions
    {
        /**
         * @return \\Codeception\\Scenario
         */
        abstract protected function getScenario();
    
        {{methods}}
    }
    
    EOF;
    protected string $method_template = <<<EOF
    
        /**
         * [!] Method is generated. Documentation taken from corresponding module.
         *
         {{doc}}
         * @see \\{{module}}::{{method}}()
         */{{attributes}}
        public function {{action}}({{params}}){{return_type}} {
            {{return}}\$this->getScenario()->runStep(new \\Codeception\\Step\\{{step}}('{{method}}', func_get_args()));
        }
    EOF;
    protected string $name;
    protected array $settings = [];
    protected array $modules = [];
    protected array $actions = [];
    protected int $num_methods = 0;
    /**
     * @var GeneratedStep[]
     */
    protected array $generated_steps = [];
    public function __construct(array $settings)
    {
        $this->name = $settings['actor'];
        $this->settings = $settings;
        $this->di = new Di();
        $this->module_container = new Module_Container($this->di, $settings);
        $this->initialize_modules();
    }
    protected function initialize_modules()
    {
        foreach (Configuration::modules($this->settings) as $module_name) {
            $this->module_container->create($module_name);
        }
        $this->modules = $this->module_container->all();
        $this->actions = $this->module_container->get_actions();
        $this->generated_steps = (array) $this->settings['step_decorators'];
    }
    public function produce(): string
    {
        $namespace = trim($this->support_namespace(), '\\');
        $methods = [];
        $code = [];
        foreach ($this->actions as $action => $module_name) {
            if (!in_array($action, $methods)) {
                $class = new ReflectionClass($this->modules[$module_name]);
                $method = $class->get_method($action);
                $code[] = $this->add_method($method);
                $methods[] = $action;
                ++$this->num_methods;
            }
        }
        return (new Template($this->template))->place('namespace', $namespace !== '' ? $namespace . '\\' : '')->place('hash', self::gen_hash($this->modules, $this->settings))->place('name', $this->name)->place('methods', implode("\n\n ", $code))->produce();
    }
    protected function add_method(ReflectionMethod $ref_method): string
    {
        $class = $ref_method->get_declaring_class();
        $params = $this->get_params_string($ref_method);
        $module = $class->get_name();
        $body = '';
        $doc = $this->add_doc($class, $ref_method);
        $doc = str_replace('/**', '', (string) $doc);
        $doc = trim(str_replace('*/', '', $doc));
        if ($doc === '') {
            $doc = '*';
        }
        $return_type = $this->create_return_type_hint($ref_method);
        if (count($ref_method->get_attributes()) > 0) {
            $attributes = "\n    " . $this->get_attributes_string($ref_method);
        }
        $method_template = (new Template($this->method_template))->place('module', $module)->place('method', $ref_method->name)->place('attributes', $attributes ?? '')->place('return_type', $return_type)->place('return', $return_type === ': void' || $return_type === ': never' ? '' : 'return ')->place('params', $params);
        if (str_starts_with($ref_method->name, 'see')) {
            $type = 'Assertion';
        } elseif (str_starts_with($ref_method->name, 'am')) {
            $type = 'Condition';
        } else {
            $type = 'Action';
        }
        $body .= $method_template->place('doc', $doc)->place('action', $ref_method->name)->place('step', $type)->produce();
        // add auto generated steps
        foreach (array_unique($this->generated_steps) as $generator) {
            if (!is_callable($generator->get_template(...))) {
                throw new Exception("Wrong configuration for generated steps. {$generator} doesn't implement \\Codeception\\Step\\GeneratedStep interface");
            }
            $template = call_user_func($generator->get_template(...), clone $method_template);
            if ($template) {
                $body .= $template->produce();
            }
        }
        return $body;
    }
    protected function get_attributes_string(ReflectionMethod $ref_method): string
    {
        $attributes = [];
        foreach ($ref_method->get_attributes() as $attribute) {
            $attributes[] = $this->stringify_attribute($attribute);
        }
        return implode("\n    ", $attributes);
    }
    protected function get_params_string(ReflectionMethod $ref_method): string
    {
        $params = [];
        foreach ($ref_method->get_parameters() as $param) {
            $type = '';
            $reflection_type = $param->get_type();
            if ($reflection_type !== null) {
                $type = $this->stringify_type($reflection_type, $ref_method->get_declaring_class()) . ' ';
            }
            $attributes = '';
            foreach ($param->get_attributes() as $attribute) {
                $attributes .= $this->stringify_attribute($attribute);
            }
            if ($attributes !== '') {
                $attributes .= ' ';
            }
            if ($param->is_optional()) {
                $params[] = $attributes . $type . '$' . $param->name . ' = ' . Reflection_Helper::get_default_value($param);
            } else {
                $params[] = $attributes . $type . '$' . $param->name;
            }
        }
        return implode(', ', $params);
    }
    /**
     * @throws ReflectionException
     */
    protected function add_doc(ReflectionClass $class, ReflectionMethod $ref_method): string|false
    {
        $doc = $ref_method->get_doc_comment();
        if (!$doc) {
            $interfaces = $class->get_interfaces();
            foreach ($interfaces as $interface) {
                $i = new ReflectionClass($interface->name);
                if ($i->has_method($ref_method->name)) {
                    $doc = $i->get_method($ref_method->name)->get_doc_comment();
                    break;
                }
            }
        }
        if (!$doc && $class->get_parent_class()) {
            $parent = new ReflectionClass($class->get_parent_class()->name);
            if ($parent->has_method($ref_method->name)) {
                return $parent->get_method($ref_method->name)->get_doc_comment();
            }
            return $doc;
        }
        return $doc;
    }
    public static function gen_hash(array $modules, array $settings): string
    {
        $actions = [];
        foreach ($modules as $module_name => $module) {
            $actions[$module_name] = get_class_methods($module::class);
        }
        return md5(Codecept::VERSION . serialize($actions) . serialize($settings['modules']) . implode(',', (array) $settings['step_decorators']));
    }
    private function create_return_type_hint(ReflectionMethod $ref_method): string
    {
        $return_type = $ref_method->get_return_type();
        if (!$return_type instanceof Reflection_Type) {
            return '';
        }
        return ': ' . $this->stringify_type($return_type, $ref_method->get_declaring_class());
    }
    private function stringify_type(Reflection_Type $type, ReflectionClass $module_class): string
    {
        if ($type instanceof ReflectionUnionType) {
            return $this->stringify_named_types($type->get_types(), $module_class, '|');
        }
        if ($type instanceof ReflectionIntersectionType) {
            return $this->stringify_named_types($type->get_types(), $module_class, '&');
        }
        if ($type instanceof ReflectionNamedType) {
            return sprintf('%s%s', $type->allows_null() && $type->get_name() !== 'mixed' ? '?' : '', self::stringify_named_type($type, $module_class));
        }
        throw new InvalidArgumentException('Unsupported type class: ' . $type::class);
    }
    /**
     * @param ReflectionNamedType[] $types
     */
    private function stringify_named_types(array $types, ReflectionClass $module_class, string $separator): string
    {
        $strings = [];
        foreach ($types as $type) {
            $strings[] = self::stringify_named_type($type, $module_class);
        }
        return implode($separator, $strings);
    }
    public static function stringify_named_type(ReflectionNamedType $type, ReflectionClass $module_class): string
    {
        $type_name = $type->get_name();
        if ($type_name === 'self') {
            $type_name = $module_class->get_name();
        } elseif ($type_name === 'parent') {
            $type_name = $module_class->get_parent_class()->get_name();
        }
        return sprintf('%s%s', $type->is_builtin() ? '' : '\\', $type_name);
    }
    private function stringify_attribute(Reflection_Attribute $attribute): string
    {
        try {
            $ref_class = new ReflectionClass($attribute->get_name());
            $name = sprintf('%s%s', $ref_class->is_user_defined() ? '\\' : '', $attribute->get_name());
        } catch (Reflection_Exception) {
            // If we can't get the class then just return what we've been given.
            $name = $attribute->get_name();
        }
        // Strip the wrapping array brackets so parameters aren't converted to arrays.
        $args = substr(Reflection_Helper::php_encode_value($attribute->get_arguments()), 1, -1);
        return '#[' . $name . '(' . $args . ')]';
    }
    public function get_num_methods(): int
    {
        return $this->num_methods;
    }
}